image: docker:latest

services:
  - docker:dind

variables:
  IMAGE_BASE: alpine
  ALPINE_VERSION: "3.9"
  PUSH_REGISTERY: registry.gitlab.com/jtco-io/pub/images

stages:
  - build

include:
  - local:  "helm/.gitlab-ci.yml"
