build-helm:
  image: docker:latest
  stage: build
#  only:
#    - schedules
  services:
    - docker:dind
#  variables:
  before_script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - cd helm

    - export BASE_IMAGE=${IMAGE_BASE}:${ALPINE_VERSION}
    - export IMAGE=${CI_REGISTRY_IMAGE}/helm:${ALPINE_VERSION}

    - echo The full image being build is
    - echo $IMAGE

    - docker pull ${BASE_IMAGE} && echo "success" || echo "doesn't exist yet"
    - docker pull ${IMAGE_VERSION} && echo "success" || echo "doesn't exist yet"
  script:
    - echo building tags latest and $IMAGE_SHA
    - >
      docker build
      --tag $IMAGE
      --build-arg ${BASE_IMAGE}
      .
  after_script:
    - export BASE_IMAGE=${IMAGE_BASE}:${ALPINE_VERSION}
    - export IMAGE=${CI_REGISTRY_IMAGE}:${ALPINE_VERSION}

    - echo pushing tags!
    - echo $BASE_IMAGE
    - echo $IMAGE

    - docker push $IMAGE

    - echo All done!
